services:
  db:
    image: postgres:18
    container_name: leave_management_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: leave_management_backend
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    environment:
      APP_NAME: ${APP_NAME}
      ENVIRONMENT: ${ENVIRONMENT}

      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}

      FRONTEND_URL: ${FRONTEND_URL}

      MAX_LOGIN_ATTEMPTS: ${MAX_LOGIN_ATTEMPTS}
      LOGIN_LOCKOUT_MINUTES: ${LOGIN_LOCKOUT_MINUTES}

    ports:
      - "8000:8000"


volumes:
  postgres_data: