"""create initial database schema

Revision ID: b3df1d3d846c
Revises: 
Create Date: 2026-10-04 12:05:23.381690
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3df1d3d846c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_annual_allowance', sa.Numeric(precision=6, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_annual_allowance >= 0', name='ck_leave_types_allowance_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_types_code'), 'leave_types', ['code'], unique=True)
    op.create_index('ix_leave_types_is_active', 'leave_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_leave_types_name'), 'leave_types', ['name'], unique=True)
    op.create_table('public_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_public_holidays_name_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_public_holidays_date', 'public_holidays', ['holiday_date'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'EMPLOYEE', name='role_enum'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('manager_id IS NULL OR manager_id <> id', name='ck_users_manager_not_self'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_manager_id', 'users', ['manager_id'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('APPROVE_LEAVE', 'REJECT_LEAVE', 'CANCEL_LEAVE', 'CREATE_USER', 'UPDATE_USER', 'DEACTIVATE_USER', 'CREATE_LEAVE_TYPE', 'UPDATE_LEAVE_TYPE', 'CREATE_HOLIDAY', 'UPDATE_HOLIDAY', name='audit_action_enum'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('leave_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('allocated_days', sa.Numeric(precision=6, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=6, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('reserved_days', sa.Numeric(precision=6, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocated_days >= 0', name='ck_leave_balance_allocated_non_negative'),
    sa.CheckConstraint('reserved_days >= 0', name='ck_leave_balance_reserved_non_negative'),
    sa.CheckConstraint('used_days + reserved_days <= allocated_days', name='ck_leave_balance_total_usage_valid'),
    sa.CheckConstraint('used_days >= 0', name='ck_leave_balance_used_non_negative'),
    sa.CheckConstraint('year >= 2000 AND year <= 2100', name='ck_leave_balance_year_valid'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'leave_type_id', 'year', name='uq_leave_balance_user_type_year')
    )
    op.create_index('ix_leave_balances_user_year', 'leave_balances', ['user_id', 'year'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_half_day', sa.Enum('NONE', 'FIRST_HALF', 'SECOND_HALF', name='half_day_type_enum'), server_default=sa.text("'NONE'"), nullable=False),
    sa.Column('end_half_day', sa.Enum('NONE', 'FIRST_HALF', 'SECOND_HALF', name='half_day_type_enum'), server_default=sa.text("'NONE'"), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leave_status_enum'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approval_comment', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('approved_by_id IS NULL OR approved_by_id <> user_id', name='ck_leave_request_cannot_approve_own_leave'),
    sa.CheckConstraint('cancelled_by_id IS NULL OR cancelled_by_id <> user_id', name='ck_leave_request_canceller_valid'),
    sa.CheckConstraint('end_date >= start_date', name='ck_leave_request_dates_valid'),
    sa.CheckConstraint('total_days > 0', name='ck_leave_request_total_days_positive'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leave_requests_approver_status', 'leave_requests', ['approved_by_id', 'status'], unique=False)
    op.create_index('ix_leave_requests_dates', 'leave_requests', ['start_date', 'end_date'], unique=False)
    op.create_index('ix_leave_requests_leave_type_status', 'leave_requests', ['leave_type_id', 'status'], unique=False)
    op.create_index('ix_leave_requests_user_status', 'leave_requests', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leave_requests_user_status', table_name='leave_requests')
    op.drop_index('ix_leave_requests_leave_type_status', table_name='leave_requests')
    op.drop_index('ix_leave_requests_dates', table_name='leave_requests')
    op.drop_index('ix_leave_requests_approver_status', table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index('ix_leave_balances_user_year', table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_manager_id', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_public_holidays_date', table_name='public_holidays')
    op.drop_table('public_holidays')
    op.drop_index(op.f('ix_leave_types_name'), table_name='leave_types')
    op.drop_index('ix_leave_types_is_active', table_name='leave_types')
    op.drop_index(op.f('ix_leave_types_code'), table_name='leave_types')
    op.drop_table('leave_types')
    # ### end Alembic commands ###