"""add leave request allocations

Revision ID: c48b031db54c
Revises: b3df1d3d846c
Create Date: 2026-10-04 14:14:44.527918
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48b031db54c'
down_revision: Union[str, Sequence[str], None] = 'b3df1d3d846c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_request_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_request_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('allocated_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocated_days > 0', name='ck_leave_request_allocation_days_positive'),
    sa.CheckConstraint('year >= 2000 AND year <= 2100', name='ck_leave_request_allocation_year_valid'),
    sa.ForeignKeyConstraint(['leave_request_id'], ['leave_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leave_request_allocations_request_year', table_name='leave_request_allocations')
    op.drop_table('leave_request_allocations')
    # ### end Alembic commands ###