from enum import Enum


class Role(str, Enum):
    ADMIN = "ADMIN"
    MANAGER = "MANAGER"
    EMPLOYEE = "EMPLOYEE"


class LeaveStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class HalfDayType(str, Enum):
    NONE = "NONE"
    FIRST_HALF = "FIRST_HALF"
    SECOND_HALF = "SECOND_HALF"


class AuditAction(str, Enum):
    APPROVE_LEAVE = "APPROVE_LEAVE"
    REJECT_LEAVE = "REJECT_LEAVE"
    CANCEL_LEAVE = "CANCEL_LEAVE"
    CREATE_USER = "CREATE_USER"
    UPDATE_USER = "UPDATE_USER"
    DEACTIVATE_USER = "DEACTIVATE_USER"
    CREATE_LEAVE_TYPE = "CREATE_LEAVE_TYPE"
    UPDATE_LEAVE_TYPE = "UPDATE_LEAVE_TYPE"
    CREATE_HOLIDAY = "CREATE_HOLIDAY"
    UPDATE_HOLIDAY = "UPDATE_HOLIDAY"
    CREATE_LEAVE = "CREATE_LEAVE"